# Generated by Django 2.1.3 on 2018-11-15 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galahad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galahad.Process')),
            ],
            bases=('galahad.process',),
        ),
        migrations.CreateModel(
            name='LoopProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galahad.Process')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            bases=('galahad.process',),
        ),
        migrations.CreateModel(
            name='SimpleProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galahad.Process')),
            ],
            bases=('galahad.process',),
        ),
        migrations.CreateModel(
            name='SplitJoinProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galahad.Process')),
                ('parallel_task_value', models.PositiveIntegerField(default=0)),
            ],
            bases=('galahad.process',),
        ),
        migrations.CreateModel(
            name='WaitProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galahad.Process')),
                ('parallel_task_value', models.PositiveIntegerField(default=0)),
            ],
            bases=('galahad.process',),
        ),
        migrations.CreateModel(
            name='WelcomeProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galahad.Process')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('galahad.process', models.Model),
        ),
    ]
