name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install binary dependencies
      run: sudo apt-get install -y python3-enchant graphviz
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install sphinxcontrib-spelling
        python setup.py develop
    - name: Build documentation
      run: python setup.py build_sphinx -W -b spelling
